[platform]
name = alpine
package_manager = apk

[packages.base]
packages = git git-crypt gnupg syncthing build-base bash

[platform_specific.1]
name = openrc
description = Init system

[services]
enable = sshd docker syncthing cronie

[openrc_services]
enable = sshd docker syncthing cronie

[apk_repos]
repos = community testing

[features]
musl = true
edge = false
