[platform]
name = debian
package_manager = apt

[packages.base]
packages = git git-crypt gnupg syncthing build-essential curl wget

[platform_specific.1]
name = docker-ce
description = Docker CE
repo = docker-ce-stable
repo_url = https://download.docker.com/linux/debian

[services]
enable = ssh docker syncthing

[apt_repos.1]
name = docker-ce-stable
url = https://download.docker.com/linux/debian
key_url = https://download.docker.com/linux/debian/gpg

[apt_repos.2]
name = syncthing
url = https://apt.syncthing.net/ syncthing stable
key_url = https://syncthing.net/release-key.gpg

[debian]
version = stable
