[platform]
name = fedora
package_manager = dnf

[packages.base]
packages = git git-crypt gnupg syncthing "@development-tools" "@dnf-plugins-core"

[packages.docker]
packages = docker-ce
 docker-ce-cli

description = Docker CE
repo_url = https://download.docker.com/linux/fedora/docker-ce.repo

[repositories.docker-ce-stable]
name = docker-ce-stable
url = https://download.docker.com/linux/fedora/docker-ce.repo
type = rpm

[services]
enable = docker
enable = syncthing
