[platform]
name = opensuse
package_manager = zypper

[packages.base]
packages = git git-crypt gnupg syncthing patterns-devel-base-devel_basis

[platform_specific.1]
name = docker
description = Docker CE
repo = docker-ce-stable

[services]
enable = sshd docker syncthing

[zypper_repos.1]
name = docker-ce-stable
url = https://download.docker.com/linux/opensuse/leap/$releasever/stable

[zypper_repos.2]
name = syncthing
url = https://download.opensuse.org/repositories/network:/syncthing/openSUSE_Leap_$releasever/

[patterns]
patterns = devel_basis devel_C_C++
