[platform]
name = raspberrypios
package_manager = apt
default_profile = minimal

[packages.base]
packages = git git-crypt gnupg syncthing build-essential

[platform_specific]
packages = 

[services]
enable = ssh syncthing

[performance]
gpu_mem = 16
overclock = false
