[platform]
name = ubuntu
package_manager = apt

external_repos = docker

gpg_url = https://download.docker.com/linux/ubuntu/gpg
repo_url = deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable

[packages.base]
packages = git git-crypt gnupg syncthing build-essential software-properties-common "@development-tools" "@linux-headers-generic"

[packages.docker]
packages = docker-ce docker-ce-cli containerd.io

[packages.platform_specific]
docker_gpg = https://download.docker.com/linux/ubuntu/gpg
docker_repo = deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable

[services]
enable = docker
enable = syncthing
