[platform]
name = void
package_manager = xbps

[repos]
repos = void-repo-nonfree void-repo-multilib

[packages.base]
packages = git git-crypt gnupg syncthing base-devel

[platform_specific.1]
name = void-repo-nonfree
description = Non-free repository

[platform_specific.2]
name = void-repo-multilib
description = Multilib repository

[services]
enable = sshd docker syncthing cronie

[runit_services]
enable = sshd docker syncthing cronie

[xbps_config]
base_system = void-lang-bash
