[platform]
name = wsl
package_manager = apt

[packages.base]
packages = git git-crypt gnupg syncthing build-essential software-properties-common wslu

[packages.docker]
packages = docker-ce docker-ce-cli containerd.io

[services]
enable = docker
enable = syncthing
